export declare const icons: {
    play: any;
    pause: any;
    replay: any;
    mute: any;
    'volume-low': any;
    'volume-high': any;
    'cc-on': any;
    'cc-off': any;
    'pip-enter': any;
    'pip-exit': any;
    'fs-enter': any;
    'fs-exit': any;
    'seek-forward': any;
    'seek-backward': any;
    'menu-chapters': any;
    'menu-settings': any;
    'menu-arrow-left': any;
    'menu-arrow-right': any;
    'menu-audio': any;
    'menu-speed': any;
    'menu-quality': any;
    'menu-captions': any;
};
